# Generated by Django 3.2.6 on 2021-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='partySize',
            field=models.IntegerField(),
        ),
    ]
