# Generated by Django 3.2.6 on 2021-10-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_cart_cartitem_dish_dishcategory_order_orderitem_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='manufacturer',
            new_name='Order',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subTotal',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
