# Generated by Django 3.2.6 on 2021-10-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20211026_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
