# Generated by Django 3.2.6 on 2021-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20211103_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_address',
            old_name='Addresss',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
